### PR TITLE
681 integrate backstage readme plugin

### PR DESCRIPTION
**Pull request by stan-dot**
expected output - README from a given repo shows up in the component page. much like https://github.com/DiamondLightSource/developer-portal/pull/693 this requires a staging setup to test properly

### CODE REVIEW

**Comment by coretl** [comment]
I know nothing about how developer portal is implemented, so unfortunately I can't review anything in this repo

**Comment by stan-dot** [comment]
todo: try out with the tokens active https://github.com/DiamondLightSource/developer-portal/pull/693#issuecomment-2196539828

**Comment by stan-dot** [comment]
> [0] Watchpack Error (watcher): Error: ENOSPC: System limit for number of file watchers reached, watch '/workspace/backstage/node_modules/@internal/plugin-viewdocs-react'

unexpected

**Comment by stan-dot** [comment]
@garryod I just tried merging and rebasing main to fix 2 conflicts that could not be resolved in the online editor but now there is even more conflicts. I am not sure what happened

**Comment by stan-dot** [comment]
will just start fresh

**Pull request closed without merging**
