### PR TITLE
add two themes for comparison

### PR DESCRIPTION
**Pull request by stan-dot**
This PR adds 2 themes as options in user settings. Those are an addition to the two (light and dark) default Backstage themes, therefore this is more of an expansion of functionality, than a modification of an existing feature/

### CODE REVIEW

**Comment by stan-dot** [comment]
now there are two Diamond themes, one light and dark. I think Backstage should use automatically depending on the system theme or using the one which is zero-indexed

**Comment by stan-dot** [comment]
make black text on white background for the light theme for real

**Comment by stan-dot** [comment]
@garryod that is not relevant after all I think, can I close the PR and the issue? Or feel free to do it

**Comment by garryod** [comment]
Sounds reasonable

**Pull request closed without merging**
